version: "3.3"
services:
  pianorecorder:
    volumes:
      -  ./app/app:/app
      -  ./app/sf:/sf
    environment:
      - PYTHONUNBUFFERED=1
  midirecorder:
    volumes:
      -  ./app/app:/app
      -  ./app/sf:/sf
    environment:
      - PYTHONUNBUFFERED=1
