version: "3.3"
services:
  pianorecorder:
    volumes:
      -  ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
  midirecorder:
    volumes:
      -  ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
