version: "3.3"
services:
  pianorecorder:
    restart: unless-stopped
    image: kevinbutchart/pianorecorder:latest
    ports:
      - 443:8443
    volumes:
      - /sys:/sys
      - /proc/device-tree:/proc/device-tree
    devices:
      - /dev/snd/seq:/dev/snd/seq
    environment:
      - PYTHONUNBUFFERED=1
    command: /app/gunicorn_start.sh
    links:
      - "midirecorder:midiplayer"
  midirecorder:
    restart: unless-stopped
    image: kevinbutchart/pianorecorder:latest
    command: /app/recorder_start.sh
    devices:
      - /dev/snd/seq:/dev/snd/seq
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 9900:9900
    volumes:
      - /sys:/sys
      - /proc/device-tree:/proc/device-tree
    command: /app/recorder_start.sh
  pianodb:
    restart: unless-stopped
    image: mongo:3.6.23
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
