version: "3.3"
services:
  pianorecorder:
    restart: unless-stopped
    image: kevinbutchart/pianorecorder:latest
    build: app
    privileged: true
    ports:
      - 80:8000
    environment:
      - PYTHONUNBUFFERED=1
    command: /app/gunicorn_start.sh
  midirecorder:
    restart: unless-stopped
    image: kevinbutchart/pianorecorder:latest
    build: app
    privileged: true
    command: /app/recorder_start.sh
  midiplayer:
    restart: unless-stopped
    image: kevinbutchart/pianorecorder:latest
    privileged: true
    build: app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 9900:9900
    volumes:
      -  ./app:/app
    command: /app/player_start.sh
  database:
    restart: unless-stopped
    image: kevinbutchart/mongodb:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    command: mongod --journal --smallfiles
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
