version: "3.3"
services:
  pianorecorder:
    restart: always
    image: kevinbutchart/pianorecorder:latest
    build: app
    privileged: true
    ports:
      - 80:8000
    volumes:
      -  $HOME/.config/pianorecorder/recordings.db:/app/recordings.db
    environment:
      - PYTHONUNBUFFERED=1
    command: /app/gunicorn_start.sh
  midirecorder:
    restart: always
    image: kevinbutchart/pianorecorder:latest
    build: app
    privileged: true
    volumes:
      -  $HOME/.config/pianorecorder/recordings.db:/app/recordings.db
    command: /app/recorder_start.sh
  database:
    image: andresvidal/rpi3-mongodb3:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
