#!/bin/bash
dirs=$(listdirs | head -n 5) 
for d in $dirs
do
    describedir "$d"
done

inotifywait -r -m -e create /var/www/html/midi |
while read dirname eventlist eventfile
do
   [[ "$eventfile" =~ .*json$ ]] && {
       DATE=$(basename "$dirname")
       echo "{\"date\":\"$DATE\",\"recordings\":["$(cat "$dirname"/"$eventfile")"]}"
   }
done
