#!/bin/bash
dirs=$(listdirs | head -n 5) 
for d in $dirs
do
    describedir "$d"
done

inotifywait -r -m -e create /var/www/html/midi |
while read dirname eventlist eventfile
do
   [[ "$eventfile" =~ .*json$ ]] && {
       DATE=$(basename "$dirname")
       FNAME="$dirname/$eventfile"
       OUT=$(cat "$FNAME")
       echo "{\"date\":\"$DATE\",\"recordings\":["$OUT"]}"
   }
done
